import type { User, Account, Opportunity, Activity } from './types';

export const users: User[] = [
  { uid: 'user-admin-1', fullName: 'Admin User', email: 'admin@aire.com', role: 'admin', active: true, createdAt: new Date(), updatedAt: new Date(), avatarUrl: 'https://picsum.photos/seed/admin/100/100' },
  { uid: 'user-jefe-1', fullName: 'Juana Manager', email: 'juana.m@aire.com', role: 'jefe', active: true, createdAt: new Date(), updatedAt: new Date(), avatarUrl: 'https://picsum.photos/seed/jefe1/100/100' },
  { uid: 'user-jefe-2', fullName: 'Pedro Boss', email: 'pedro.b@aire.com', role: 'jefe', active: true, createdAt: new Date(), updatedAt: new Date(), avatarUrl: 'https://picsum.photos/seed/jefe2/100/100' },
  { uid: 'user-asesor-1', fullName: 'Ana Ventas', email: 'ana.v@aire.com', role: 'asesor', active: true, createdAt: new Date(), updatedAt: new Date(), avatarUrl: 'https://picsum.photos/seed/asesor1/100/100' },
  { uid: 'user-asesor-2', fullName: 'Carlos Cierra', email: 'carlos.c@aire.com', role: 'asesor', active: true, createdAt: new Date(), updatedAt: new Date(), avatarUrl: 'https://picsum.photos/seed/asesor2/100/100' },
  { uid: 'user-asesor-3', fullName: 'Beatriz Bueno', email: 'beatriz.b@aire.com', role: 'asesor', active: true, createdAt: new Date(), updatedAt: new Date(), avatarUrl: 'https://picsum.photos/seed/asesor3/100/100' },
];

export const accounts: Account[] = [
  {
    accountId: 'acc-1',
    displayName: 'Comercio del Litoral',
    industry: 'comercio',
    city: 'Santa Fe',
    province: 'Santa Fe',
    ownerUid: 'user-asesor-1',
    status: 'activo',
    createdAt: new Date(),
    updatedAt: new Date(),
    contacts: [{ id: 'contact-1', firstName: 'Roberto', lastName: 'Gomez', role: 'Gerente', email: 'rgomez@comerciolitoral.com', phone: '342-1234567', preferredChannel: 'email' }]
  },
  {
    accountId: 'acc-2',
    displayName: 'Servicios Digitales SF',
    industry: 'servicios',
    city: 'Rosario',
    province: 'Santa Fe',
    ownerUid: 'user-asesor-2',
    status: 'activo',
    createdAt: new Date(),
    updatedAt: new Date(),
    contacts: [{ id: 'contact-2', firstName: 'Laura', lastName: 'Perez', role: 'CEO', email: 'laura@sdsf.com', phone: '341-7654321', preferredChannel: 'whatsapp' }]
  },
  {
    accountId: 'acc-3',
    displayName: 'Gobierno Provincial',
    industry: 'gobierno',
    city: 'Santa Fe',
    province: 'Santa Fe',
    ownerUid: 'user-asesor-3',
    status: 'activo',
    createdAt: new Date(),
    updatedAt: new Date(),
    contacts: [{ id: 'contact-3', firstName: 'Miguel', lastName: 'Juarez', role: 'Secretario', email: 'prensa@gobiernosf.com', phone: '342-1122334', preferredChannel: 'tel' }]
  }
];

export const opportunities: Opportunity[] = [
  {
    opportunityId: 'opp-1',
    accountId: 'acc-1',
    accountName: 'Comercio del Litoral',
    ownerUid: 'user-asesor-1',
    stage: 'propuesta',
    source: 'inbound',
    platform: 'radio',
    estAmount: 5000,
    closeProbability: 0.6,
    expectedCloseDate: new Date(new Date().setDate(new Date().getDate() + 30)),
    nextAction: 'Enviar propuesta detallada',
    nextActionDate: new Date(new Date().setDate(new Date().getDate() + 2)),
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    opportunityId: 'opp-2',
    accountId: 'acc-2',
    accountName: 'Servicios Digitales SF',
    ownerUid: 'user-asesor-2',
    stage: 'negociación',
    source: 'referido',
    platform: 'digital',
    estAmount: 12000,
    closeProbability: 0.8,
    expectedCloseDate: new Date(new Date().setDate(new Date().getDate() + 15)),
    nextAction: 'Llamada de seguimiento por contrato',
    nextActionDate: new Date(new Date().setDate(new Date().getDate() + 5)),
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    opportunityId: 'opp-3',
    accountId: 'acc-3',
    accountName: 'Gobierno Provincial',
    ownerUid: 'user-asesor-3',
    stage: 'ganado',
    source: 'evento',
    platform: 'mixto',
    estAmount: 25000,
    closeProbability: 1,
    expectedCloseDate: new Date(new Date().setDate(new Date().getDate() - 10)),
    nextAction: 'Iniciar orden de pauta',
    nextActionDate: new Date(new Date().setDate(new Date().getDate() -1)),
    createdAt: new Date(new Date().setDate(new Date().getDate() - 20)),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 10))
  },
  {
    opportunityId: 'opp-4',
    accountId: 'acc-1',
    accountName: 'Comercio del Litoral',
    ownerUid: 'user-asesor-1',
    stage: 'lead',
    source: 'redes',
    platform: 'tv',
    estAmount: 8000,
    closeProbability: 0.1,
    expectedCloseDate: new Date(new Date().setDate(new Date().getDate() + 60)),
    nextAction: 'Primer contacto',
    nextActionDate: new Date(new Date().setDate(new Date().getDate() + 1)),
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    opportunityId: 'opp-5',
    accountId: 'acc-2',
    accountName: 'Servicios Digitales SF',
    ownerUid: 'user-asesor-2',
    stage: 'perdido',
    source: 'llamado',
    platform: 'radio',
    estAmount: 3000,
    closeProbability: 0,
    expectedCloseDate: new Date(new Date().setDate(new Date().getDate() - 5)),
    nextAction: 'Archivar',
    nextActionDate: new Date(new Date().setDate(new Date().getDate())),
    lostReason: 'Presupuesto insuficiente',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 30)),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 5))
  },
    {
    opportunityId: 'opp-6',
    accountId: 'acc-1',
    accountName: 'Comercio del Litoral',
    ownerUid: 'user-asesor-1',
    stage: 'contacto',
    source: 'inbound',
    platform: 'digital',
    estAmount: 4500,
    closeProbability: 0.3,
    expectedCloseDate: new Date(new Date().setDate(new Date().getDate() + 45)),
    nextAction: 'Agendar reunión de descubrimiento',
    nextActionDate: new Date(new Date().setDate(new Date().getDate() + 7)),
    createdAt: new Date(),
    updatedAt: new Date()
  },
];

export const activities: Activity[] = [
    {
        activityId: 'act-1',
        entityType: 'opportunity',
        entityId: 'opp-1',
        type: 'email',
        summary: 'Enviado email de presentación con brochure de Radio.',
        when: new Date(new Date().setDate(new Date().getDate() - 5)),
        createdBy: 'user-asesor-1',
        createdAt: new Date(new Date().setDate(new Date().getDate() - 5)),
    },
    {
        activityId: 'act-2',
        entityType: 'opportunity',
        entityId: 'opp-2',
        type: 'reunión',
        summary: 'Reunión con Laura Perez para discutir estrategia digital. Mostró mucho interés.',
        when: new Date(new Date().setDate(new Date().getDate() - 7)),
        createdBy: 'user-asesor-2',
        nextAction: 'Preparar propuesta basada en la reunión',
        nextActionDate: new Date(new Date().setDate(new Date().getDate() - 6)),
        createdAt: new Date(new Date().setDate(new Date().getDate() - 7)),
    },
    {
        activityId: 'act-3',
        entityType: 'opportunity',
        entityId: 'opp-2',
        type: 'llamada',
        summary: 'Llamada de seguimiento sobre la propuesta. Pidieron ajustar el presupuesto.',
        when: new Date(new Date().setDate(new Date().getDate() - 2)),
        createdBy: 'user-asesor-2',
        createdAt: new Date(new Date().setDate(new Date().getDate() - 2)),
    },
    {
        activityId: 'act-4',
        entityType: 'account',
        entityId: 'acc-3',
        type: 'nota',
        summary: 'Recordar que el contacto principal para campañas de verano es Miguel Juarez.',
        when: new Date(new Date().setDate(new Date().getDate() - 10)),
        createdBy: 'user-asesor-3',
        createdAt: new Date(new Date().setDate(new Date().getDate() - 10)),
    },
];
