// This file is automatically generated. Do not modify it manually.

// This is the Firebase configuration for your web app.
// It is safe to expose this configuration to the client.
const firebaseConfig = {
  "projectId": "studio-4698748512-76e6b",
  "appId": "1:161460412233:web:97f65cf463f7b192e00498",
  "apiKey": "AIzaSyDXD3WyDEhAwGSLOJZ7DtE58NZh7_LyRLw",
  "authDomain": "studio-4698748512-76e6b.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "161460412233"
};

export default firebaseConfig;
