// This file is automatically generated. Do not modify it manually.

// This is the Firebase configuration for your web app.
// It is safe to expose this configuration to the client.
const firebaseConfig = {
  apiKey: "AIzaSyDhGY79PE-XiH8W1eAESRyBEFmytwdkKEk",
  authDomain: "crm-aire.firebaseapp.com",
  projectId: "crm-aire",
  storageBucket: "crm-aire.firebasestorage.app",
  messagingSenderId: "128258561335",
  appId: "1:128258561335:web:05b7cf4b43e6eda24136b2",
  measurementId: "G-FC821FXKVW"
};

export default firebaseConfig;
